### ISSUE TITLE
体验了一下滑动的效果,感觉不是很灵敏,要是操作快一点的话会子滑动组件会不生效.

### ISSUE THREAD

**Issue by wuweijian1997** [bladeofgod/cloud_music#2]
RT,要是快速切换会不生效,这个是flutter的缺陷吗?尤其是子滑动组件和子非滑动组件交互滑动就会经常出现这个问题.

**Comment by bladeofgod** [comment]
> RT,要是快速切换会不生效,这个是flutter的缺陷吗?尤其是子滑动组件和子非滑动组件交互滑动就会经常出现这个问题.

这个是pageview的设计导致的，网易的app也是这样，如果需要你的那个需求的话， 那确实要自己定制了。
从产品角度讲，应该是对用户操作的区域划分的界线上出现了分歧。

**Comment by wuweijian1997** [comment]
有空学习一下,thx.
